export const API_ROUTES = {
  ADMIN: {
    EMPLOYERS: '/api/admin/employers',
    EMPLOYER_STATUS: (id) => `/api/admin/employers/${id}/status`,
    EMPLOYER_JOBS: (id) => `/api/admin/employers/${id}/jobs`,
    CANDIDATES: '/api/admin/candidates',
    CANDIDATE_BY_ID: (id) => `/api/admin/candidates/${id}`,
    CANDIDATE_STATUS: (id) => `/api/admin/candidates/${id}/status`,
    CANDIDATE_ASSIGN: '/api/admin/candidates/assign',
    CANDIDATE_DUPLICATES: '/api/admin/candidates/duplicates',
    JOBS: '/api/admin/jobs',
    JOB_MATCHES: (id) => `/api/admin/jobs/${id}/matches`,
    SUB_ADMINS: '/api/admin/sub-admins',
    AUTH: {
      LOGIN: '/api/admin/auth/login',
      ME: '/api/admin/auth/me',
      CHANGE_PASSWORD: '/api/admin/auth/change-password',
    },
  },
  SUB_ADMIN: {
    CANDIDATES: '/api/sub-admin/candidates',
    CANDIDATE_BY_ID: (id) => `/api/sub-admin/candidates/${id}`,
    CANDIDATE_STATUS: (id) => `/api/sub-admin/candidates/${id}/status`,
    CANDIDATE_NOTES: (id) => `/api/sub-admin/candidates/${id}/notes`,
    ME_STATS: '/api/sub-admin/me/stats',
  },
  SUPER_ADMIN: {
    ADMINS: '/api/super-admin/admins',
    ADMIN_BY_ID: (id) => `/api/super-admin/admins/${id}`,
    ADMIN_ACTIVATE: (id) => `/api/super-admin/admins/${id}/activate`,
    ADMIN_DEACTIVATE: (id) => `/api/super-admin/admins/${id}/deactivate`,
    SUB_ADMINS: '/api/super-admin/sub-admins',
    SUB_ADMIN_BY_ID: (id) => `/api/super-admin/sub-admins/${id}`,
    SUB_ADMIN_ACTIVATE: (id) => `/api/super-admin/sub-admins/${id}/activate`,
    SUB_ADMIN_DEACTIVATE: (id) => `/api/super-admin/sub-admins/${id}/deactivate`,
    SMTP_STATUS: '/api/super-admin/smtp-status',
    ANALYTICS: {
      SUMMARY: '/api/super-admin/analytics/summary',
      FUNNEL: '/api/super-admin/analytics/funnel',
      SOURCE_BREAKDOWN: '/api/super-admin/analytics/source-breakdown',
      DISTRICT_DEMAND: '/api/super-admin/analytics/district-demand',
      SUB_ADMIN_LEADERBOARD: '/api/super-admin/analytics/sub-admin-leaderboard',
      TIME_TO_PLACEMENT: '/api/super-admin/analytics/time-to-placement',
      AGING: '/api/super-admin/analytics/aging',
      PLACEMENT_RATE: '/api/super-admin/analytics/placement-rate',
      ACTIVITY_LOGS: '/api/super-admin/analytics/activity-logs',
    },
  },
};
