export const STATES_AND_DISTRICTS = {
  "Tamil Nadu": [
    'Ariyalur', 'Chengalpattu', 'Chennai', 'Coimbatore', 'Cuddalore', 'Dharmapuri',
    'Dindigul', 'Erode', 'Kallakurichi', 'Kancheepuram', 'Karur', 'Krishnagiri', 'Madurai',
    'Mayiladuthurai', 'Nagapattinam', 'Namakkal', 'Nilgiris', 'Perambalur', 'Pudukkottai',
    'Ramanathapuram', 'Ranipet', 'Salem', 'Sivaganga', 'Tenkasi', 'Thanjavur', 'Theni',
    'Thoothukudi', 'Tiruchirappalli', 'Tirunelveli', 'Tirupathur', 'Tiruppur', 'Tiruvallur',
    'Tiruvannamalai', 'Tiruvarur', 'Vellore', 'Viluppuram', 'Virudhunagar'
  ],
  "Andhra Pradesh": [
    'Anantapur', 'Chittoor', 'East Godavari', 'Guntur', 'Krishna', 'Kurnool', 'Prakasam',
    'Srikakulam', 'Sri Potti Sriramulu Nellore', 'Visakhapatnam', 'Vizianagaram', 'West Godavari', 'YSR Kadapa'
  ],
  "Karnataka": [
    'Bagalkot', 'Bangalore Rural', 'Bangalore Urban', 'Belgaum', 'Bellary', 'Bidar',
    'Chamarajanagar', 'Chikkaballapur', 'Chikkamagaluru', 'Chitradurga', 'Dakshina Kannada',
    'Davanagere', 'Dharwad', 'Gadag', 'Gulbarga', 'Hassan', 'Haveri', 'Kodagu', 'Kolar',
    'Koppal', 'Mandya', 'Mysore', 'Raichur', 'Ramanagara', 'Shimoga', 'Tumkur', 'Udupi',
    'Uttara Kannada', 'Vijayapura', 'Yadgir'
  ],
  "Kerala": [
    'Alappuzha', 'Ernakulam', 'Idukki', 'Kannur', 'Kasaragod', 'Kollam', 'Kottayam',
    'Kozhikode', 'Malappuram', 'Palakkad', 'Pathanamthitta', 'Thiruvananthapuram', 'Thrissur', 'Wayanad'
  ],
  "Telangana": [
    'Adilabad', 'Bhadradri Kothagudem', 'Hyderabad', 'Jagtial', 'Jangaon', 'Jayashankar Bhupalpally',
    'Jogulamba Gadwal', 'Kamareddy', 'Karimnagar', 'Khammam', 'Kumuram Bheem Asifabad', 'Mahabubabad',
    'Mahabubnagar', 'Mancherial', 'Medak', 'Medchal-Malkajgiri', 'Mulugu', 'Nagarkurnool', 'Nalgonda',
    'Narayanpet', 'Nirmal', 'Nizamabad', 'Peddapalli', 'Rajanna Sircilla', 'Rangareddy', 'Sangareddy',
    'Siddipet', 'Suryapet', 'Vikarabad', 'Wanaparthy', 'Warangal Rural', 'Warangal Urban', 'Yadadri Bhuvanagiri'
  ],
  "Puducherry": [
    'Karaikal', 'Mahe', 'Puducherry', 'Yanam'
  ],
  "Maharashtra": [
    'Ahmednagar', 'Akola', 'Amravati', 'Aurangabad', 'Beed', 'Bhandara', 'Buldhana',
    'Chandrapur', 'Dhule', 'Gadchiroli', 'Gondia', 'Hingoli', 'Jalgaon', 'Jalna', 'Kolhapur',
    'Latur', 'Mumbai City', 'Mumbai Suburban', 'Nagpur', 'Nanded', 'Nandurbar', 'Nashik',
    'Osmanabad', 'Palghar', 'Parbhani', 'Pune', 'Raigad', 'Ratnagiri', 'Sangli', 'Satara',
    'Sindhudurg', 'Solapur', 'Thane', 'Wardha', 'Washim', 'Yavatmal'
  ],
  "Gujarat": [
    'Ahmedabad', 'Amreli', 'Anand', 'Aravalli', 'Banaskantha', 'Bharuch', 'Bhavnagar',
    'Botad', 'Chhota Udepur', 'Dahod', 'Dang', 'Devbhumy Dwarka', 'Gandhinagar', 'Gir Somnath',
    'Jamnagar', 'Junagadh', 'Kheda', 'Kutch', 'Mahisagar', 'Mehsana', 'Morbi', 'Narmada',
    'Navsari', 'Panchmahal', 'Patan', 'Porbandar', 'Rajkot', 'Sabarkantha', 'Surat',
    'Surendranagar', 'Tapi', 'Vadodara', 'Valsad'
  ],
  "Delhi": [
    'Central Delhi', 'East Delhi', 'New Delhi', 'North Delhi', 'North East Delhi',
    'North West Delhi', 'Shahdara', 'South Delhi', 'South East Delhi', 'South West Delhi', 'West Delhi'
  ]
};

export const TN_COLLEGES = [
  "Anna University, Chennai",
  "Madras University, Chennai",
  "Bharathiar University, Coimbatore",
  "Madurai Kamaraj University, Madurai",
  "Bharathidasan University, Tiruchirappalli",
  "Manonmaniam Sundaranar University, Tirunelveli",
  "Alagappa University, Karaikudi",
  "Annamalai University, Chidambaram",
  "Periyar University, Salem",
  "Thiruvalluvar University, Vellore",
  "Tamil Nadu Agricultural University (TNAU), Coimbatore",
  "Tamil Nadu Veterinary and Animal Sciences University (TANUVAS), Chennai",
  "Tamil Nadu Dr. M.G.R. Medical University, Chennai",
  "Tamil Nadu Dr. Ambedkar Law University, Chennai",
  "Tamil Nadu Physical Education and Sports University, Chennai",
  "Tamil University, Thanjavur",
  "Gandhigram Rural Institute, Dindigul",
  "Sathyabama Institute of Science and Technology, Chennai",
  "SRM Institute of Science and Technology, Chennai",
  "VIT University, Vellore",
  "Amrita Vishwa Vidyapeetham, Coimbatore",
  "SASTRA Deemed University, Thanjavur",
  "Kalasalingam Academy of Research and Education, Srivilliputhur",
  "Karunya Institute of Technology and Sciences, Coimbatore",
  "B.S. Abdur Rahman Crescent Institute of Science and Technology, Chennai",
  "Vinayaka Mission's Research Foundation, Salem",
  "Avinashilingam Institute for Home Science and Higher Education for Women, Coimbatore",
  "Loyola College, Chennai",
  "Madras Christian College (MCC), Chennai",
  "Presidency College, Chennai",
  "St. Joseph's College, Tiruchirappalli",
  "American College, Madurai",
  "PSG College of Arts and Science, Coimbatore",
  "Stella Maris College, Chennai",
  "Women's Christian College (WCC), Chennai",
  "Ethiraj College for Women, Chennai",
  "Bishop Heber College, Tiruchirappalli",
  "Jamal Mohamed College, Tiruchirappalli",
  "National College, Tiruchirappalli",
  "Government Arts College, Coimbatore",
  "Government Arts College, Salem",
  "Government Arts College, Kumbakonam",
  "Government Arts College, Nandanam, Chennai",
  "Queen Mary's College, Chennai",
  "Sacred Heart College, Tirupattur",
  "Sourashtra College, Madurai",
  "Thiagarajar College, Madurai",
  "Lady Doak College, Madurai",
  "Madura College, Madurai",
  "Sri Ramakrishna Mission Vidyalaya College of Arts and Science, Coimbatore",
  "Kongu Arts and Science College, Erode",
  "Vellalar College for Women, Erode",
  "Bishop Appasamy College of Arts and Science, Coimbatore",
  "Gobi Arts & Science College, Gobichettipalayam",
  "Ayya Nadar Janaki Ammal College, Sivakasi",
  "Standard Fireworks Rajaratnam College for Women, Sivakasi",
  "Sarah Tucker College, Tirunelveli",
  "St. Xavier's College, Palayamkottai",
  "Sadakathullah Appa College, Tirunelveli",
  "College of Engineering, Guindy (CEG), Chennai",
  "Madras Institute of Technology (MIT), Chromepet, Chennai",
  "Alagappa Chettiar Government College of Engineering and Technology, Karaikudi",
  "Government College of Technology (GCT), Coimbatore",
  "PSG College of Technology, Coimbatore",
  "Thiagarajar College of Engineering (TCE), Madurai",
  "Coimbatore Institute of Technology (CIT), Coimbatore",
  "Government College of Engineering, Salem",
  "Government College of Engineering, Tirunelveli",
  "Government College of Engineering, Bargur",
  "Government College of Engineering, Bodinayakkanur",
  "Government College of Engineering, Srirangam",
  "National Institute of Technology (NIT), Tiruchirappalli",
  "Indian Institute of Technology (IIT), Madras",
  "Kongu Engineering College, Erode",
  "Bannari Amman Institute of Technology, Sathyamangalam",
  "K.L.N. College of Engineering, Madurai",
  "Mepco Schlenk Engineering College, Sivakasi",
  "Sri Sivasubramaniya Nadar (SSN) College of Engineering, Chennai",
  "St. Joseph's College of Engineering, Chennai",
  "Rajalakshmi Engineering College, Chennai",
  "Easwari Engineering College, Chennai",
  "Sri Krishna College of Engineering and Technology, Coimbatore",
  "Kumaraguru College of Technology, Coimbatore",
  "Sona College of Technology, Salem",
  "Francis Xavier Engineering College, Tirunelveli",
  "National Engineering College, Kovilpatti",
  "PSNA College of Engineering and Technology, Dindigul",
  "Central Polytechnic College, Chennai",
  "Government Polytechnic College, Coimbatore",
  "Government Polytechnic College, Madurai",
  "Government Polytechnic College, Tiruchirappalli",
  "Government Polytechnic College, Tuticorin",
  "Government Polytechnic College, Nagercoil",
  "Government Polytechnic College, Krishnagiri",
  "PSG Polytechnic College, Coimbatore",
  "Murugappa Polytechnic College, Chennai",
  "Government Industrial Training Institute (ITI), Guindy, Chennai",
  "Government Industrial Training Institute (ITI), Coimbatore",
  "Government Industrial Training Institute (ITI), Madurai",
  "Government Industrial Training Institute (ITI), Trichy"
];
